# Generated by Django 3.2 on 2023-12-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sexo',
            field=models.CharField(choices=[('h', 'MEN'), ('c', 'CHILDREN'), ('m', 'WOMEN')], default='5', max_length=1),
        ),
    ]
