# Generated by Django 3.2 on 2023-12-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20231204_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sexo',
            field=models.CharField(choices=[('c', 'children'), ('m', 'women'), ('h', 'men')], default='5', max_length=1),
        ),
    ]
