# Generated by Django 3.2 on 2023-11-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_facturadetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='direccion_envio',
            field=models.TextField(null=True),
        ),
    ]
