# Generated by Django 3.2 on 2023-11-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_factura_direccion_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='nro_factura',
        ),
        migrations.AddField(
            model_name='factura',
            name='nro_pedido',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
