# Generated by Django 3.2 on 2023-12-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20231204_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='matrial',
            field=models.CharField(choices=[('o', 'oro'), ('p', 'plata'), ('c', 'cobre')], default='5', max_length=1),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('p', 'PAGADO'), ('$', 'SOLICITADO')], default='5', max_length=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sexo',
            field=models.CharField(choices=[('h', 'men'), ('m', 'women'), ('c', 'children')], default='5', max_length=1),
        ),
    ]
