# Generated by Django 3.2 on 2023-11-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20231125_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('p', 'PAGADO'), ('$', 'SOLICITADO')], default='5', max_length=1),
        ),
    ]
