# Generated by Django 3.2 on 2023-11-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_factura_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('$', 'SOLICITADO'), ('p', 'PAGADO')], default='5', max_length=1),
        ),
    ]
